export const teams = {
    "teams": [
        "San Antonio Spurs",
        "Los Angeles Lakers",
        "Cleveland Cavaliers",
        "New York Knicks",
        "Boston Celtics",
        "Indiana Pacers",
        "Phoenix Suns",
        "Houston Rockets",
        "Milwaukee Bucks",
        "Philadelphia 76ers",
        "Detroit Pistons",
        "Oklahoma City Thunder",
        "Brooklyn Nets",
        "Denver Nuggets",
        "Sacramento Kings",
        "Los Angeles Clippers",
        "Chicago Bulls",
        "Washington Wizards",
        "Atlanta Hawks",
        "Golden State Warriors",
        "Portland Trail Blazers",
        "Utah Jazz",
        "Dallas Mavericks",
        "Charlotte Hornets",
        "Miami Heat",
        "Orlando Magic",
        "Minnesota Timberwolves",
        "Toronto Raptors",
        "Memphis Grizzlies",
        "New Orleans Pelicans"
    ]
}